name: Build & Deploy to OpenShift

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_REGISTRY: quay.io
      IMAGE_REPO: ${{ secrets.QUAY_REPO }} # e.g. myorg/fastapi-service
      IMAGE_TAG: dev
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: fastapi-demo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Quay
        run: echo "${{ secrets.QUAY_PASSWORD }}" | docker login $IMAGE_REGISTRY -u "${{ secrets.QUAY_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          docker build -t $IMAGE_REGISTRY/$IMAGE_REPO:$IMAGE_TAG .
          docker push $IMAGE_REGISTRY/$IMAGE_REPO:$IMAGE_TAG

      - name: Install oc CLI
        run: |
          curl -sLo oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xzf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Login to OpenShift
        run: oc login $OPENSHIFT_SERVER --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify

      - name: Apply Kustomize overlay
        run: |
          oc apply -k https://github.com/<your-org>/<platform-apps-repo>/apps/fastapi-service/overlays/dev
